###
### View Change Fault Tolerance Tests
### Phases:
###  - 'start'
###  - 'contribute'
###  - 'share'
###  - 'publish'
###  - 'wait'
### Default MagicBlock:
###   sharders: ["sharder-1"]
###   miners: ["miner-1", "miner-2", "miner-3", "miner-4"]
###   k_percent: 0.75 of registered
###   t_percent: 0.51 of active
###   x_percent: 0.70 of min(max_n, num_dkg_miners)
###   min_s: 1, max_s: 2
###   min_n: 3, max_n: 7
###
### Outside Miners: ["miner-5", "miner-6", "miner-7", "miner-8"]
### Outside Sharders: ["sharder-3"]
###
### Phase Rounds:
###   start_rounds: 50
###   contribute_rounds: 50
###   share_rounds: 50
###   publish_rounds: 50
###   wait_rounds: 50
###

---
enable:
#   - "Outside miner comes up and goes down"

sets:
  - name: "Outside miner comes up and goes down"
    tests:
      - "Outside miner comes up in phase 'start' and goes down in phase 'start'"
      - "Outside miner comes up in phase 'start' and goes down in phase 'contribute'"
      - "Outside miner comes up in phase 'start' and goes down in phase 'share'"
      - "Outside miner comes up in phase 'start' and goes down in phase 'publish'"
      - "Outside miner comes up in phase 'start' and goes down in phase 'wait'"
      - "Outside miner comes up in phase 'contribute' and goes down in phase 'contribute'"
      - "Outside miner comes up in phase 'contribute' and goes down in phase 'share'"
      - "Outside miner comes up in phase 'contribute' and goes down in phase 'publish'"
      - "Outside miner comes up in phase 'contribute' and goes down in phase 'wait'"
      - "Outside miner comes up in phase 'share' and goes down in phase 'share'"
      - "Outside miner comes up in phase 'share' and goes down in phase 'publish'"
      - "Outside miner comes up in phase 'share' and goes down in phase 'wait'"
      - "Outside miner comes up in phase 'publish' and goes down in phase 'publish'"
      - "Outside miner comes up in phase 'publish' and goes down in phase 'wait'"
      - "Outside miner comes up in phase 'wait' and goes down in phase 'wait'"

tests:
  # Outside miner comes up and goes down
  - name: "Outside miner comes up in phase 'start' and goes down in phase 'start'"
    flow:
      - set_monitor: "sharder-1"
      - cleanup_bc: {}
      - start_lock: ["miner-5"]
      - start_lock: ["sharder-1"]
      - start_lock: ["miner-1", "miner-2", "miner-3"]
      - unlock: ["sharder-1", "miner-1", "miner-2", "miner-3"]
      - wait_add:
          sharders: ["sharder-1"]
          miners: ["miner-1", "miner-2", "miner-3"]
      #- wait_sharder_keep:
      #    sharders: ["sharder-1"] # sync nodes
      - wait_phase:
          phase: "start"
      - unlock: ["miner-5"]
      - wait_add:
          miners: ["miner-5"]
      - wait_round:
          shift: 15
      - stop: ["miner-5"]
      - wait_view_change:
          timeout: "10m"
          expect_magic_block:
            number: 2
            sharders: ["sharder-1"]
            miners: ["miner-1", "miner-2", "miner-3"]

  - name: "Outside miner comes up in phase 'start' and goes down in phase 'contribute'"
    flow:
      - set_monitor: "sharder-1"
      - cleanup_bc: {}
      - start_lock: ["miner-5"]
      - start_lock: ["sharder-1"]
      - start_lock: ["miner-1", "miner-2", "miner-3"]
      - unlock: ["sharder-1", "miner-1", "miner-2", "miner-3"]
      - wait_add:
          sharders: ["sharder-1"]
          miners: ["miner-1", "miner-2", "miner-3"]
      #- wait_sharder_keep:
      #    sharders: ["sharder-1"] # sync nodes
      - wait_phase:
          phase: "start"
      - unlock: ["miner-5"]
      - wait_add:
          miners: ["miner-5"]
      - wait_phase:
          phase: "contribute"
      - stop: ["miner-5"]
      - wait_view_change:
          timeout: "10m"
          expect_magic_block:
            number: 2
            sharders: ["sharder-1"]
            miners: ["miner-1", "miner-2", "miner-3"]

  - name: "Outside miner comes up in phase 'start' and goes down in phase 'share'"
    flow:
      - set_monitor: "sharder-1"
      - cleanup_bc: {}
      - start_lock: ["miner-5"]
      - start_lock: ["sharder-1"]
      - start_lock: ["miner-1", "miner-2", "miner-3"]
      - unlock: ["sharder-1", "miner-1", "miner-2", "miner-3"]
      - wait_add:
          sharders: ["sharder-1"]
          miners: ["miner-1", "miner-2", "miner-3"]
      #- wait_sharder_keep:
      #    sharders: ["sharder-1"] # sync nodes
      - wait_phase:
          phase: "start"
      - unlock: ["miner-5"]
      - wait_add:
          miners: ["miner-5"]
      - wait_phase:
          phase: "share"
      - stop: ["miner-5"]
      - wait_view_change:
          timeout: "10m"
          expect_magic_block:
            number: 2
            sharders: ["sharder-1"]
            miners: ["miner-1", "miner-2", "miner-3"]

  - name: "Outside miner comes up in phase 'start' and goes down in phase 'publish'"
    flow:
      - set_monitor: "sharder-1"
      - cleanup_bc: {}
      - start_lock: ["miner-5"]
      - start_lock: ["sharder-1"]
      - start_lock: ["miner-1", "miner-2", "miner-3"]
      - unlock: ["sharder-1", "miner-1", "miner-2", "miner-3"]
      - wait_add:
          sharders: ["sharder-1"]
          miners: ["miner-1", "miner-2", "miner-3"]
      #- wait_sharder_keep:
      #    sharders: ["sharder-1"] # sync nodes
      - wait_phase:
          phase: "start"
      - unlock: ["miner-5"]
      - wait_add:
          miners: ["miner-5"]
      - wait_phase:
          phase: "publish"
      - stop: ["miner-5"]
      - wait_view_change:
          timeout: "10m"
          expect_magic_block:
            number: 2
            sharders: ["sharder-1"]
            miners: ["miner-1", "miner-2", "miner-3"]

  - name: "Outside miner comes up in phase 'start' and goes down in phase 'wait'"
    flow:
      - set_monitor: "sharder-1"
      - cleanup_bc: {}
      - start_lock: ["miner-5"]
      - start_lock: ["sharder-1"]
      - start_lock: ["miner-1", "miner-2", "miner-3"]
      - unlock: ["sharder-1", "miner-1", "miner-2", "miner-3"]
      - wait_add:
          sharders: ["sharder-1"]
          miners: ["miner-1", "miner-2", "miner-3"]
      #- wait_sharder_keep:
      #    sharders: ["sharder-1"] # sync nodes
      - wait_phase:
          phase: "start"
      - unlock: ["miner-5"]
      - wait_add:
          miners: ["miner-5"]
      - wait_phase:
          phase: "wait"
      - stop: ["miner-5"]
      - wait_view_change:
          timeout: "10m"
          expect_magic_block:
            number: 2
            sharders: ["sharder-1"]
            miners: ["miner-1", "miner-2", "miner-3", "miner-5"]

  - name: "Outside miner comes up in phase 'contribute' and goes down in phase 'contribute'"
    flow:
      - set_monitor: "sharder-1"
      - cleanup_bc: {}
      - start_lock: ["miner-5"]
      - start_lock: ["sharder-1"]
      - start_lock: ["miner-1", "miner-2", "miner-3"]
      - unlock: ["sharder-1", "miner-1", "miner-2", "miner-3"]
      - wait_add:
          sharders: ["sharder-1"]
          miners: ["miner-1", "miner-2", "miner-3"]
      #- wait_sharder_keep:
      #    sharders: ["sharder-1"] # sync nodes
      - wait_phase:
          phase: "contribute"
      - unlock: ["miner-5"]
      - wait_add:
          miners: ["miner-5"]
      - wait_round:
          shift: 15
      - stop: ["miner-5"]
      - wait_view_change:
          timeout: "10m"
          expect_magic_block:
            number: 2
            sharders: ["sharder-1"]
            miners: ["miner-1", "miner-2", "miner-3"]

  - name: "Outside miner comes up in phase 'contribute' and goes down in phase 'share'"
    flow:
      - set_monitor: "sharder-1"
      - cleanup_bc: {}
      - start_lock: ["miner-5"]
      - start_lock: ["sharder-1"]
      - start_lock: ["miner-1", "miner-2", "miner-3"]
      - unlock: ["sharder-1", "miner-1", "miner-2", "miner-3"]
      - wait_add:
          sharders: ["sharder-1"]
          miners: ["miner-1", "miner-2", "miner-3"]
      #- wait_sharder_keep:
      #    sharders: ["sharder-1"] # sync nodes
      - wait_phase:
          phase: "contribute"
      - unlock: ["miner-5"]
      - wait_add:
          miners: ["miner-5"]
      - wait_phase:
          phase: "share"
      - stop: ["miner-5"]
      - wait_view_change:
          timeout: "10m"
          expect_magic_block:
            number: 2
            sharders: ["sharder-1"]
            miners: ["miner-1", "miner-2", "miner-3"]

  - name: "Outside miner comes up in phase 'contribute' and goes down in phase 'publish'"
    flow:
      - set_monitor: "sharder-1"
      - cleanup_bc: {}
      - start_lock: ["miner-5"]
      - start_lock: ["sharder-1"]
      - start_lock: ["miner-1", "miner-2", "miner-3"]
      - unlock: ["sharder-1", "miner-1", "miner-2", "miner-3"]
      - wait_add:
          sharders: ["sharder-1"]
          miners: ["miner-1", "miner-2", "miner-3"]
      #- wait_sharder_keep:
      #    sharders: ["sharder-1"] # sync nodes
      - wait_phase:
          phase: "contribute"
      - unlock: ["miner-5"]
      - wait_add:
          miners: ["miner-5"]
      - wait_phase:
          phase: "publish"
      - stop: ["miner-5"]
      - wait_view_change:
          timeout: "10m"
          expect_magic_block:
            number: 2
            sharders: ["sharder-1"]
            miners: ["miner-1", "miner-2", "miner-3"]

  - name: "Outside miner comes up in phase 'contribute' and goes down in phase 'wait'"
    flow:
      - set_monitor: "sharder-1"
      - cleanup_bc: {}
      - start_lock: ["miner-5"]
      - start_lock: ["sharder-1"]
      - start_lock: ["miner-1", "miner-2", "miner-3"]
      - unlock: ["sharder-1", "miner-1", "miner-2", "miner-3"]
      - wait_add:
          sharders: ["sharder-1"]
          miners: ["miner-1", "miner-2", "miner-3"]
      #- wait_sharder_keep:
      #    sharders: ["sharder-1"] # sync nodes
      - wait_phase:
          phase: "contribute"
      - unlock: ["miner-5"]
      - wait_add:
          miners: ["miner-5"]
      - wait_phase:
          phase: "wait"
      - stop: ["miner-5"]
      - wait_view_change:
          timeout: "10m"
          expect_magic_block:
            number: 2
            sharders: ["sharder-1"]
            miners: ["miner-1", "miner-2", "miner-3"]

  - name: "Outside miner comes up in phase 'share' and goes down in phase 'share'"
    flow:
      - set_monitor: "sharder-1"
      - cleanup_bc: {}
      - start_lock: ["miner-5"]
      - start_lock: ["sharder-1"]
      - start_lock: ["miner-1", "miner-2", "miner-3"]
      - unlock: ["sharder-1", "miner-1", "miner-2", "miner-3"]
      - wait_add:
          sharders: ["sharder-1"]
          miners: ["miner-1", "miner-2", "miner-3"]
      #- wait_sharder_keep:
      #    sharders: ["sharder-1"] # sync nodes
      - wait_phase:
          phase: "share"
      - unlock: ["miner-5"]
      - wait_add:
          miners: ["miner-5"]
      - wait_round:
          shift: 15
      - stop: ["miner-5"]
      - wait_view_change:
          timeout: "10m"
          expect_magic_block:
            number: 2
            sharders: ["sharder-1"]
            miners: ["miner-1", "miner-2", "miner-3"]

  - name: "Outside miner comes up in phase 'share' and goes down in phase 'publish'"
    flow:
      - set_monitor: "sharder-1"
      - cleanup_bc: {}
      - start_lock: ["miner-5"]
      - start_lock: ["sharder-1"]
      - start_lock: ["miner-1", "miner-2", "miner-3"]
      - unlock: ["sharder-1", "miner-1", "miner-2", "miner-3"]
      - wait_add:
          sharders: ["sharder-1"]
          miners: ["miner-1", "miner-2", "miner-3"]
      #- wait_sharder_keep:
      #    sharders: ["sharder-1"] # sync nodes
      - wait_phase:
          phase: "share"
      - unlock: ["miner-5"]
      - wait_add:
          miners: ["miner-5"]
      - wait_phase:
          phase: "publish"
      - stop: ["miner-5"]
      - wait_view_change:
          timeout: "10m"
          expect_magic_block:
            number: 2
            sharders: ["sharder-1"]
            miners: ["miner-1", "miner-2", "miner-3"]

  - name: "Outside miner comes up in phase 'share' and goes down in phase 'wait'"
    flow:
      - set_monitor: "sharder-1"
      - cleanup_bc: {}
      - start_lock: ["miner-5"]
      - start_lock: ["sharder-1"]
      - start_lock: ["miner-1", "miner-2", "miner-3"]
      - unlock: ["sharder-1", "miner-1", "miner-2", "miner-3"]
      - wait_add:
          sharders: ["sharder-1"]
          miners: ["miner-1", "miner-2", "miner-3"]
      #- wait_sharder_keep:
      #    sharders: ["sharder-1"] # sync nodes
      - wait_phase:
          phase: "share"
      - unlock: ["miner-5"]
      - wait_add:
          miners: ["miner-5"]
      - wait_phase:
          phase: "wait"
      - stop: ["miner-5"]
      - wait_view_change:
          timeout: "10m"
          expect_magic_block:
            number: 2
            sharders: ["sharder-1"]
            miners: ["miner-1", "miner-2", "miner-3"]

  - name: "Outside miner comes up in phase 'publish' and goes down in phase 'publish'"
    flow:
      - set_monitor: "sharder-1"
      - cleanup_bc: {}
      - start_lock: ["miner-5"]
      - start_lock: ["sharder-1"]
      - start_lock: ["miner-1", "miner-2", "miner-3"]
      - unlock: ["sharder-1", "miner-1", "miner-2", "miner-3"]
      - wait_add:
          sharders: ["sharder-1"]
          miners: ["miner-1", "miner-2", "miner-3"]
      #- wait_sharder_keep:
      #    sharders: ["sharder-1"] # sync nodes
      - wait_phase:
          phase: "publish"
      - unlock: ["miner-5"]
      - wait_add:
          miners: ["miner-5"]
      - wait_round:
          shift: 15
      - stop: ["miner-5"]
      - wait_view_change:
          timeout: "10m"
          expect_magic_block:
            number: 2
            sharders: ["sharder-1"]
            miners: ["miner-1", "miner-2", "miner-3"]

  - name: "Outside miner comes up in phase 'publish' and goes down in phase 'wait'"
    flow:
      - set_monitor: "sharder-1"
      - cleanup_bc: {}
      - start_lock: ["miner-5"]
      - start_lock: ["sharder-1"]
      - start_lock: ["miner-1", "miner-2", "miner-3"]
      - unlock: ["sharder-1", "miner-1", "miner-2", "miner-3"]
      - wait_add:
          sharders: ["sharder-1"]
          miners: ["miner-1", "miner-2", "miner-3"]
      #- wait_sharder_keep:
      #    sharders: ["sharder-1"] # sync nodes
      - wait_phase:
          phase: "publish"
      - unlock: ["miner-5"]
      - wait_add:
          miners: ["miner-5"]
      - wait_phase:
          phase: "wait"
      - stop: ["miner-5"]
      - wait_view_change:
          timeout: "10m"
          expect_magic_block:
            number: 2
            sharders: ["sharder-1"]
            miners: ["miner-1", "miner-2", "miner-3"]

  - name: "Outside miner comes up in phase 'wait' and goes down in phase 'wait'"
    flow:
      - set_monitor: "sharder-1"
      - cleanup_bc: {}
      - start_lock: ["miner-5"]
      - start_lock: ["sharder-1"]
      - start_lock: ["miner-1", "miner-2", "miner-3"]
      - unlock: ["sharder-1", "miner-1", "miner-2", "miner-3"]
      - wait_add:
          sharders: ["sharder-1"]
          miners: ["miner-1", "miner-2", "miner-3"]
      #- wait_sharder_keep:
      #    sharders: ["sharder-1"] # sync nodes
      - wait_phase:
          phase: "wait"
      - unlock: ["miner-5"]
      - wait_add:
          miners: ["miner-5"]
      - wait_round:
          shift: 15
      - stop: ["miner-5"]
      - wait_view_change:
          timeout: "10m"
          expect_magic_block:
            number: 2
            sharders: ["sharder-1"]
            miners: ["miner-1", "miner-2", "miner-3"]
