miners:
- id: 0045b7774b14fd3ed0cca861c927680b4a770900f35b293a4bf32e4fccff5a6d
  public_key: e065fc02aaf7aaafaebe5d2dedb9c7c1d63517534644434b813cb3bdab0f94a0
  n2n_ip: 198.18.0.71
  public_ip: localhost
  port: 7071
  description: localhost.m0

- id: 4155d4fd4d0172ec44cb87fa58712c4b220bf24de8953a4de26c067d65850c9d
  public_key: cb9babd82cf33b77568cb74b8c235b7de3b0807bd7e336c9a79c8872dd31a9a7
  n2n_ip: 198.18.0.72
  public_ip: localhost
  port: 7072
  description: localhost.m1

- id: de6b11d94da372f7fca80292ac5274d639d74f91c1214af08a1b385ead58bdbb
  public_key: ead2cc189369c8761340806055670002998679627f744cbd4129357fbc962296
  n2n_ip: 198.18.0.73
  public_ip: localhost
  port: 7073
  description: localhost.m2

sharders:
- id: 275d9cf6e0947643954188d39a09d64aac004457a310900043fcd16a3976d3d8
  public_key: 303d8bfbf2421cf4a4cc3ce02b3e2d465a45c2164628bcb9b73703c69a80b6ca
  n2n_ip: 198.18.0.81
  public_ip: localhost
  port: 7171
  description: localhost.s0

- id: 57fe3b4d898e60f3c8c9f7a356c2d0680caf17370101be119ed2cc028f42fd41
  public_key: b3814c5118ff618d8c3af7d8096ca9557c026ddb915d867ef696b092fa742cb7
  n2n_ip: 198.18.0.82
  public_ip: localhost
  port: 7172
  # description: localhost.s1

- id: 853bb6eb72dbed82f0883fe42f93214a28b199f494818752c593b0ffd3baa046
  public_key: c423b3543aa0eae177b6e0442eeaa73b527bf346065b1f999498b9c2d78138da
  n2n_ip: 198.18.0.83
  public_ip: localhost
  port: 7173 
  # description: localhost.s2
