initialStates:
  # miners
  - id: edb90b850f2e7e7cbd0a1fa370fdcc5cd378ffbec95363a7bc0e5a98b8ba5759
    tokens: 10000000000

  - id: 31810bd1258ae95955fb40c7ef72498a556d3587121376d9059119d280f34929
    tokens: 10000000000

  - id: 585732eb076d07455fbebcf3388856b6fd00449a25c47c0f72d961c7c4e7e7c2
    tokens: 10000000000

  - id: bfa64c67f49bceec8be618b1b6f558bdbaf9c100fd95d55601fa2190a4e548d8
    tokens: 10000000000

  - id: 8877e3da19b4cb51e59b4646ec7c0cf4849bc7b860257d69ddbf753b9a981e1b
    tokens: 100000000000

  - id: 53add50ff9501014df2cbd698c673f85e5785281cebba8772a64a6e74057d328
    tokens: 100000000000

  - id: 8b2b5cd7e26db28ebbc3da1652b1967f1029a35fbed1dd330ec9652e62dde464
    tokens: 100000000000

  - id: dda909a7f6c77562a836f71d0d8385842abfc5eaf1a4b52007a31ea5e38c49c2
    tokens: 100000000000

  - id: 5ea78acd3d32117ab7c0744b0d3d3e61b6a4591d32ab81eb623c732e709e9e7f
    tokens: 100000000000

  # sharders
  - id: 57b416fcda1cf82b8a7e1fc3a47c68a94e617be873b5383ea2606bda757d3ce4
    tokens: 10000000000

  - id: b098d2d56b087ee910f3ee2d2df173630566babb69f0be0e2e9a0c98d63f0b0b
    tokens: 10000000000

  - id: d9558143f8e976126367603bff34125f5eb94720df8d7acefffdd66675d134c2
    tokens: 10000000000

  - id: 600396361b3c9efc3a1ad85df6930163591be04a8c12bc5226414d34a81cb8e5
    tokens: 10000000000

  # blobbers
  - id: f65af5d64000c7cd2883f4910eb69086f9d6e6635c744e62afcfab58b938ee25
    tokens: 100000000000

  - id: 7a90e6790bcd3d78422d7a230390edc102870fe58c15472073922024985b1c7d
    tokens: 100000000000

  - id: 2f051ca6447d8712a020213672bece683dbd0d23a81fdf93ff273043a0764d18
    tokens: 100000000000

  - id: 2a4d5a5c6c0976873f426128d2ff23a060ee715bccf0fd3ca5e987d57f25b78e
    tokens: 100000000000

  - id: 429c05b461f60a8db4329750810d3d40a49c0b4d95dd414bac1926f263321fe0
    tokens: 100000000000

  - id: f34e784da180ac6097bdcd243548f6c192599968c93e0cbf4c565d78cbcf8933
    tokens: 100000000000

#  validators
  - id: 41313b795d2c057b6277801e9ed277b444770c2af75f5209afd00bd07c72cc0b
    tokens: 100000000000

  - id: ab549edb7cea822dab0b460f65dcde85f698c1e97d730e3ffc6b0f8b576b65bd
    tokens: 100000000000

  - id: 86cf791f03f01e3e4d318b1ca009a51c91dd43f7cf3c87a32f531b609cc5044b
    tokens: 100000000000

  - id: 823cb45de27dfe739b320dcf6449e5fdea35c60804fd81d6f22c005042cfb337
    tokens: 100000000000

  - id: 0c1748cb83e7417a1399b334efcf325fcfedce66ba57123e581627a8e681fb95
    tokens: 100000000000

  - id: 109a99cbaff4b180abd9cace80afc27946e9a64030197914e61b2a2a04e3c02f
    tokens: 100000000000
  
  # authorizers
  - id: 1746b06bb09f55ee01b33b5e2e055d6cc7a900cb57c0a3a5eaabb8a0e7745802
    tokens: 10000000000

  - id: 47c534abb2bcb33e9944aee9a0df0e0adc4c0b659b9499aa656920975c38a80a
    tokens: 10000000000

  - id: 7f2097074f678d08146e5585d6965b04307939fee0457ea18c4242bff197c65a
    tokens: 10000000000

  # faucetsc
  - id: 6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d3
    tokens: 20000000000000000

initialStakes:
  # blobbers
  - provider_id: f65af5d64000c7cd2883f4910eb69086f9d6e6635c744e62afcfab58b938ee25
    provider_type: blobber
    client_id: 894f7cd245757019337cd61a597849c58791c184435125654166d34405b245f4
    tokens: 50000000000
