initialStates:
  # miners
  - id: edb90b850f2e7e7cbd0a1fa370fdcc5cd378ffbec95363a7bc0e5a98b8ba5759
    tokens: 10000000000

  - id: 31810bd1258ae95955fb40c7ef72498a556d3587121376d9059119d280f34929
    tokens: 10000000000

  - id: 585732eb076d07455fbebcf3388856b6fd00449a25c47c0f72d961c7c4e7e7c2
    tokens: 10000000000

  - id: bfa64c67f49bceec8be618b1b6f558bdbaf9c100fd95d55601fa2190a4e548d8
    tokens: 10000000000

  - id: 8877e3da19b4cb51e59b4646ec7c0cf4849bc7b860257d69ddbf753b9a981e1b
    tokens: 100000000000

  - id: 53add50ff9501014df2cbd698c673f85e5785281cebba8772a64a6e74057d328
    tokens: 100000000000

  - id: 8b2b5cd7e26db28ebbc3da1652b1967f1029a35fbed1dd330ec9652e62dde464
    tokens: 100000000000

  - id: dda909a7f6c77562a836f71d0d8385842abfc5eaf1a4b52007a31ea5e38c49c2
    tokens: 100000000000

  - id: 5ea78acd3d32117ab7c0744b0d3d3e61b6a4591d32ab81eb623c732e709e9e7f
    tokens: 100000000000

  # sharders
  - id: 57b416fcda1cf82b8a7e1fc3a47c68a94e617be873b5383ea2606bda757d3ce4
    tokens: 10000000000

  - id: b098d2d56b087ee910f3ee2d2df173630566babb69f0be0e2e9a0c98d63f0b0b
    tokens: 10000000000

  - id: d9558143f8e976126367603bff34125f5eb94720df8d7acefffdd66675d134c2
    tokens: 10000000000

  - id: 600396361b3c9efc3a1ad85df6930163591be04a8c12bc5226414d34a81cb8e5
    tokens: 10000000000

  # faucetsc
  - id: 6dba10422e368813802877a85039d3985d96760ed844092319743fb3a76712d3
    tokens: 20000000000000000

initialStakes:
  # blobbers
  - provider_id: f65af5d64000c7cd2883f4910eb69086f9d6e6635c744e62afcfab58b938ee25
    provider_type: blobber
    client_id: 894f7cd245757019337cd61a597849c58791c184435125654166d34405b245f4
    tokens: 50000000000

  - provider_id: f65af5d64000c7cd2883f4910eb69086f9d6e6635c744e62afcfab58b938ee25
    provider_type: blobber
    client_id: 894f7cd245757019337cd61a597849c58791c184435125654166d34405b245f4
    tokens: 10000000000
