name: config_change_PR

on:
  push:
   branches: 
     - staging
   paths:
      - docker.local/config/0chain.yaml
      - docker.local/config/sc.yaml
  
  pull_request:
    branches: 
      - staging
    types:
      - closed
    paths:
      - docker.local/config/0chain.yaml
      - docker.local/config/sc.yaml
   
jobs:
  ConfigChange:
    runs-on: arc-runner
    steps:
      - uses: actions/checkout@v1

      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v18.4

      - name: "Clone 0helm"
        if: ${{ contains(steps.changed-files.outputs.modified_files, 'docker.local/config/0chain.yaml') || contains(steps.changed-files.outputs.modified_files, 'docker.local/config/sc.yaml') }}
        uses: actions/checkout@v2
        with:
          ref: one-pool-staging-test
          repository: 0chain/0helm
          fetch-depth: 1
          path: ./0helm
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: "Copy 0chain.yaml and sc.yaml in 0helm one-pool-staging-test branch"
        if: ${{ contains(steps.changed-files.outputs.modified_files, 'docker.local/config/0chain.yaml') || contains(steps.changed-files.outputs.modified_files, 'docker.local/config/sc.yaml') }}
        run: |
          mkdir -p 0helm/updated_configs
          touch 0helm/updated_configs/0chain.yaml
          touch 0helm/updated_configs/sc.yaml
          cp docker.local/config/0chain.yaml 0helm/updated_configs/0chain.yaml
          cp docker.local/config/sc.yaml 0helm/updated_configs/sc.yaml

      - name: Push Updated Code in 0helm one-pool-staging-test branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./0helm/updated_configs
          destination_dir: updated_configs
          publish_branch: one-pool-staging-test
          keep_files: true
          external_repository: "0chain/0helm"
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"

  PR:
    runs-on: 'arc-runner'
    environment: 'HelmRepo'
    needs: [ConfigChange]
    steps:
      - name: Raise PR
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.ACCESS_TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/0chain/0helm/actions/workflows/raise_pr.yaml/dispatches \
          -d '{"ref": "staging"}'

          
      
